"""add group curator

Revision ID: 42120a585a8f
Revises: 4332e0d9a8a2
Create Date: 2026-10-07 17:23:32.619247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42120a585a8f'
down_revision = '4332e0d9a8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curator', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('curator')

    # ### end Alembic commands ###
