"""add student enrolled_at

Revision ID: 8f2899ec5a65
Revises: 800d075a19ea
Create Date: 2026-10-07 17:01:10.402433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2899ec5a65'
down_revision = '800d075a19ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrolled_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('enrolled_at')

    # ### end Alembic commands ###
